-- One row per (language, kind, interaction id, install): the last value an install sent for it.
--   kind 'name'  : key is an interaction id, value is the game's name of the interaction in that language.
--   kind 'group' : key is an interaction id, value is the label of the group it belongs to in that language.
-- The install id is a random uuid generated by the extension, it only lets us count how many different installs agree.
CREATE TABLE IF NOT EXISTS submissions (
    lang    INTEGER NOT NULL,
    kind    TEXT    NOT NULL CHECK (kind IN ('name', 'group')),
    key     INTEGER NOT NULL,
    value   TEXT    NOT NULL,
    install TEXT    NOT NULL,
    ts      INTEGER NOT NULL,
    PRIMARY KEY (lang, kind, key, install)
);
